CREATE SCHEMA INTERSTELLAR_TRANSPORT;

CREATE TABLE INTERSTELLAR_TRANSPORT.PLANET(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NODE VARCHAR(2) UNIQUE NOT NULL,
  NAME VARCHAR(50),
  PRIMARY KEY (ID)
);

CREATE TABLE INTERSTELLAR_TRANSPORT.ROUTE(
  ID INTEGER NOT NULL,
  PLANET_ORIGIN VARCHAR(2),
  PLANET_DESTINATION VARCHAR(2),
  DISTANCE DOUBLE,
  PRIMARY KEY (ID)
);

CREATE TABLE INTERSTELLAR_TRANSPORT.ROUTE_TRAFFIC(
  ROUTE_ID INTEGER NOT NULL,
  DELAY DOUBLE,
  PRIMARY KEY (ROUTE_ID),
  CONSTRAINT ROUTE_FK FOREIGN KEY (ROUTE_ID) REFERENCES INTERSTELLAR_TRANSPORT.ROUTE(ID)
);

