swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: planet-controller
    description: Planet Controller
  - name: route-controller
    description: Route Controller
paths:
  /planets:
    get:
      tags:
        - planet-controller
      summary: getAllPlanets
      operationId: getAllPlanetsUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/PlanetDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - planet-controller
      summary: createPlanet
      operationId: createPlanetUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: newPlanet
          description: newPlanet
          required: true
          schema:
            $ref: '#/definitions/PlanetDto'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/planets/{id}':
    get:
      tags:
        - planet-controller
      summary: planetDetails
      operationId: planetDetailsUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Planet'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - planet-controller
      summary: updatePlanetDetails
      operationId: updatePlanetDetailsUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: updatedPlanet
          description: updatedPlanet
          required: true
          schema:
            $ref: '#/definitions/Planet'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - planet-controller
      summary: removePlanet
      operationId: removePlanetUsingDELETE
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /routes:
    get:
      tags:
        - route-controller
      summary: getAllRoutes
      operationId: getAllRoutesUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/RouteDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - route-controller
      summary: createRoute
      operationId: createRouteUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: newRoute
          description: newRoute
          required: true
          schema:
            $ref: '#/definitions/RouteDto'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/routes/{id}':
    get:
      tags:
        - route-controller
      summary: routeDetails
      operationId: routeDetailsUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Route'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - route-controller
      summary: updateRouteDetails
      operationId: updateRouteDetailsUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
        - in: body
          name: updatedRoute
          description: updatedRoute
          required: true
          schema:
            $ref: '#/definitions/Route'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - route-controller
      summary: removeRoute
      operationId: removeRouteUsingDELETE
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
definitions:
  Planet:
    type: object
    properties:
      entityId:
        type: integer
        format: int64
      name:
        type: string
      node:
        type: string
  PlanetDto:
    type: object
    properties:
      entityId:
        type: integer
        format: int64
      name:
        type: string
      node:
        type: string
  Route:
    type: object
    properties:
      delay:
        type: number
        format: double
      destination:
        type: string
      distance:
        type: number
        format: double
      id:
        type: integer
        format: int32
      origin:
        type: string
  RouteDto:
    type: object
    properties:
      delay:
        type: number
        format: double
      destination:
        type: string
      distance:
        type: number
        format: double
      id:
        type: integer
        format: int32
      origin:
        type: string
